# Generated by Django 5.0.1 on 2024-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_rating_alter_booking_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='packageName',
            field=models.CharField(default='{Package name}', max_length=20),
        ),
    ]
