# Generated by Django 5.0.1 on 2024-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_packagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='packageName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
